# markdown
md = [ "**/*.md", "*.md" ]

# python
py = [ "**/*.py", "*.py" ]

# shell
sh = [ "**/*.sh", "*.sh", "hooks/*" ]

# toml
toml = [ "**/*.toml", "*.toml" ]

# yaml
yaml = [ "**/*.yaml", "**/*.yml", "*.yaml", "*.yml" ]

# json
json = [ "**/*.json", "*.json" ]

# javascript
javascript = [ "**/*.js", "**/*.mjs", "*.js", "*.mjs" ]

# Dockerfile
dockerfile = [ "**/Dockerfile", "Dockerfile" ]

# NO LINT, NO FOMRMAT
none = [
  "**/requirements.txt",
  "*.cron",
  ".editorconfig",
  ".flake8",
  ".gitignore",
  ".gitmodules",
  ".yamlfmt",
  "LICENSE",
  "requirements.txt",
]
